- name: app setup
  include_role:
    name: common 
    tasks_from: app-setup

- name: nodejs setup 
  include_role:
     name: common
     tasks_from: nodejs

- name: systemd setup 
  include_role:
    name: common
    tasks_from: systemd.yaml        

- name: deployment 
  tags:
  - deployment 
  import_role: 
    name: common
    tasks_from: deployment.yaml